Промежуточная проверка
vikvanton/react-burger pull request #1
Opened 2022-11-26 21:39 UTC by vikvanton

2022-11-26 22:35 UTC, ArslanDev666 requested changes
## Code Review

Здравствуйте!

### **Работа отклонена. Но я проверил частично код.**

- Проект не запускается и не собирается. Не хватает многих зависимостей.

  https://yadi.sk/d/VcxDm-0SKoHiSw - также не хватает библиотеки prop-types, но почему-то в ошибках этого нет.

2022-11-26 22:35 UTC, ArslanDev666 commented on src/components/app/app.jsx
> +        bun: {},
**Надо исправить:**

Если данных нет, то следует записывать null а не пустой объект

2022-11-26 22:35 UTC, ArslanDev666 commented on src/components/app/app.jsx
> +        <>
**Можно лучше:**

Лучше вынести индексы в массив, и просто через map сделать новый из элементов.

2022-11-26 22:35 UTC, ArslanDev666 commented on src/components/app/app.jsx
> +                    sauce.push(newItem);
**Можно лучше:**

Объявляйте данные там, где они используются (BurgerConstructor, BurgerIngredietns).

2022-11-26 22:35 UTC, ArslanDev666 commented on src/components/burger-ingredients/burger-ingredients.jsx
> +    const [current, setCurrent] = React.useState("Булки");
**Надо исправить:**

Тут лучше использовать английские значения, а не русские.

2022-11-26 22:35 UTC, ArslanDev666 commented on src/components/burger-ingredients/burger-ingredients.jsx
> +function BurgerIngredients(props) {
**Можно лучше:** 

Используйте деструктуризацию пропсов, чтобы было видно, какие пропсы использует компонент.

2022-11-26 22:35 UTC, ArslanDev666 commented on src/components/burger-ingredients/burger-ingredients.jsx
> +                    </ul>
**Можно лучше:**

у каждой категории ингредиентов дублируется верстка, лучше вынести отдельный компонент ingredients-category и переиспользовать его

2022-11-26 22:35 UTC, ArslanDev666 commented on src/components/burger-ingredients/burger-ingredients.jsx
> +});
**Можно лучше:**

во многих компонентах дублируется описание PropTypes ингредиента
Лучше вынести его в отдельный файл (можно создать файл prop-types.js в папке utils) и переиспользовать описание пропсов ингрединта, а не дублировать

2022-11-26 22:35 UTC, ArslanDev666 commented on src/components/burger-ingredients/burger-ingredients.jsx
> +    bun: PropTypes.arrayOf(propObjectShape).isRequired,
**Надо исправить:**

Необходимо указывать .isRequired как у элемента массива, так и у самого массива в PropTypes.
Пример как правильно:

```js
data: PropTypes.arrayOf(ingredientTypes.isRequired).isRequired;
```

2022-11-26 22:35 UTC, ArslanDev666 commented on src/components/burger-ingredients-item/burger-ingredients-item.jsx
> +    ingredient: PropTypes.shape({
**Можно лучше:** 

Похожее замечание в burger-ingredients

2022-11-26 22:35 UTC, ArslanDev666 commented on src/components/burger-constructor/burger-constructor.jsx
> +const propObjectShape = PropTypes.shape({
**Можно лучше:** 

Похожее замечание в burger-ingredients

2022-11-26 22:35 UTC, ArslanDev666 commented on src/components/burger-constructor/burger-constructor.jsx
> +        list: PropTypes.arrayOf(propObjectShape).isRequired,
**Надо исправить:**

Похожее замечание в burger-ingredients

2022-11-26 22:35 UTC, ArslanDev666 commented on src/components/burger-constructor/burger-constructor.jsx
> +                        {"7500"}
**Можно лучше:** 

Немного не понял, зачем оборачивать это в фигурные скобки)

2022-11-28 03:01 UTC, ArslanDev666 approved these changes
## Code Review

Здравствуйте!

Отличная работа.

Приложение начинает обрастать функционалом и уже постепенно проглядывается картина готового продукта.

### **Вы молодец! Приступайте к выполнению финального этапа задания.**

- Декомпозиция файлов по директориям - практически соответствует описанию;
- Сборка и запуск проекта выполняются без ошибок;
- Используются функциональные компоненты;
- Используются css-modules, что тоже очень удобно и является хорошей практикой;

### **Сделает код лучше:**

- При клике на соответствующий таб должен происходить плавный скролл к нужному разделу в списке ингредиентов.

- Перед отправкой работы убедитесь в том, что весь неиспользуемый код удален.

- Стоит обращать внимание на предупреждения в терминале, в котором запущен проект. Это хорошие рекомендации, которых следовало бы придерживаться. В противном случае, лучше отключить линтер у строки (куска кода) eslint-disable. Так же добавить комментарий (TODO), объясняющий причину блокировки линтера в данном месте. Суть в том, что мы стараемся писать более чистый код, а если видим, что порой выскакивают предупреждения того же линтера, то оставляем комментарий, объясняющий причину. В коммерческой разработке, когда есть целая команда разработчиков, работающих над одним проектом, эта рекомендация послужит правилом хорошего тона. Неплохая статься по поводу локального отключения линтера: https://learn.coderslang.com/ru/0023-eslint-disable-for-specific-lines-files-and-folders

### **_Подробно эти и более мелкие замечания, отмечены в коде._**

#### **Хочу напомнить, что работа может быть принята, только после исправления всех "Надо исправить". Перед отправкой на ревью, проверьте работоспособность проекта и наличие возможных ошибок в консоли браузера (кнопка F12).**

2022-11-28 03:01 UTC, ArslanMustafin commented on src/components/app-header/app-header.jsx
> +                    <li
**Надо исправить**

Оберните иконку и текст в ссылку в шапке в ссылку `<a href="#">`

Например

```html
<a href="#" class="......"> <BurgerIcon type="primary" /> Конструктор </a>
```

2022-11-28 03:01 UTC, ArslanMustafin commented on src/components/burger-constructor/burger-constructor.jsx
> +            list: [...[1, 2, 3, 4, 5, 7, 10].map((item) => ingredients[item])],
**Можно лучше:**

Нам можно не применять тут деструктуризацию, т.к map по умолчанию возвращает новый массив.

2022-11-28 03:01 UTC, ArslanDev666 commented on src/components/burger-ingredients/burger-ingredients.jsx
> +                    index === 10
**Можно лучше:** 

попробуйте сделать условие попроще, а вообще не особо над этим запаривайтесь, данный функционал будет только через спринт) и он будет реализовываться немного по другому.

2022-11-28 11:35 UTC, vikvanton commented on src/components/burger-ingredients/burger-ingredients.jsx
> +                    index === 10
Пока не буду исправлять по вашему совету

2022-11-28 11:42 UTC, vikvanton commented
Исправил замечания и добавил скролл по табам. И еще я не совсем понял процедуру: Вы должны принять работу  по первой части на платформе практикума и потом я сливаю в главную ветку, создаю новую ветку sprint1/step2 и начинаю вторую часть? Или я уже могу сливать этот пуллреквест,

2022-11-28 12:01 UTC, ArslanDev666 commented
Работа принимается только после финальной сдачи, ваш PR по предварительной части я апрувнул)) вы создаёте новую ветку, новый PR, и  на платформе просто отправляете ссылку на новый PR ))
Вроде понятно объяснил :) но если что-то не будет понятно, можете всегда уточнить у своего наставника.

2022-11-28 12:09 UTC, merged